import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import SideBar from "./components/sideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto px-2 md:px-4">
          <Header />
          <main className="mt-9  flex flex-col md:flex-row justify-between">
            {children}

            <SideBar />
          </main>
        </div>
      </body>
    </html>
  );
}
